---
language: go
go: "1.11"

before_install:
  - go get -u github.com/mitchellh/gox
  - go get -u golang.org/x/tools/cmd/goimports

script: go build

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      script: ./.travis/deploy.sh
      go: "1.11"
      deploy:
        skip_cleanup: true
        provider: releases
        api_key: $GH_RELEASE_TOKEN
        file:
          - tlself_macos.zip
        on:
          tags: true
